# Generated by Django 5.0.3 on 2024-05-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nome_projeto',
            new_name='projectName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='responsavel',
            new_name='responsible',
        ),
    ]
