# Generated by Django 5.0.3 on 2024-04-25 19:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandFactor1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('fd1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandFactor2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tueNumber', models.IntegerField()),
                ('fd2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demand', models.IntegerField()),
                ('circuitBreaker', models.IntegerField()),
                ('phase', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('grounding', models.IntegerField()),
                ('conduit', models.IntegerField()),
                ('typePhase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Tue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
    ]
